import { createFileRoute, Link } from "@tanstack/react-router";
import { Footer } from "@/components/Footer";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Mystery Unlock" },
      {
        name: "description",
        content:
          "Mystery Unlock Privacy Policy. Learn how we collect, use, and protect your data.",
      },
    ],
  }),
  component: PrivacyPage,
});

const C = {
  bg: "#F7FBFD",
  light: "#D6E6EF",
  primary: "#7FA6B8",
  primaryDark: "#5e8a9e",
  dark: "#2A3E4B",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2
        className="text-xl font-bold"
        style={{ color: C.dark, fontFamily: "'Space Grotesk', sans-serif" }}
      >
        {title}
      </h2>
      <div className="space-y-2 text-sm leading-relaxed" style={{ color: `${C.dark}cc` }}>
        {children}
      </div>
    </section>
  );
}

function Bullet({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex items-start gap-2">
      <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: C.primary }} />
      <span>{children}</span>
    </li>
  );
}

function PrivacyPage() {
  return (
    <div
      className="min-h-[100dvh] flex flex-col"
      style={{ background: C.bg, fontFamily: "'DM Sans', sans-serif" }}
    >
      <div className="flex-1 px-6 py-12">
        <div className="max-w-3xl mx-auto">
          <Link
            to="/"
            className="inline-flex items-center gap-1.5 text-sm mb-8 hover:opacity-70 transition-opacity"
            style={{ color: `${C.dark}99` }}
          >
            <svg viewBox="0 0 16 16" className="w-3.5 h-3.5 fill-current" aria-hidden>
              <path d="M10 12L6 8l4-4" stroke="currentColor" strokeWidth="1.5" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
            Back to home
          </Link>

          <header className="mb-10">
            <div
              className="inline-block text-xs font-bold uppercase tracking-widest px-3 py-1 rounded-full mb-4"
              style={{ background: C.light, color: C.primaryDark }}
            >
              Legal
            </div>
            <h1
              className="text-4xl font-black tracking-tight mb-3"
              style={{ color: C.dark, fontFamily: "'Space Grotesk', sans-serif" }}
            >
              Privacy Policy
            </h1>
            <p className="text-sm" style={{ color: `${C.dark}80` }}>
              Last updated: July 2, 2026 · Effective immediately
            </p>
          </header>

          <div
            className="rounded-2xl p-5 mb-10 text-sm"
            style={{ background: C.light, color: `${C.dark}cc` }}
          >
            This Privacy Policy describes how <strong style={{ color: C.dark }}>Mystery Unlock</strong> ("we", "us", or "our") collects, uses, and shares information about you when you use our services at{" "}
            <a href="https://mysteryunlock.com" className="underline" style={{ color: C.primaryDark }}>mysteryunlock.com</a>.
            By using Mystery Unlock, you agree to the practices described in this policy.
          </div>

          <div className="space-y-10">
            <Section title="1. Information We Collect">
              <p>We collect information you provide directly and information generated automatically through your use of our platform.</p>
              <p className="font-semibold" style={{ color: C.dark }}>Account information (shop owners):</p>
              <ul className="space-y-1.5 list-none pl-0">
                <Bullet>Email address used to create and manage your account</Bullet>
                <Bullet>Shop name, URL slug, and logo you configure</Bullet>
                <Bullet>Prize wheel content you create (prize names, weights, colours)</Bullet>
                <Bullet>Billing information (processed by our payment provider — we do not store card numbers)</Bullet>
              </ul>
              <p className="font-semibold" style={{ color: C.dark }}>Customer data (end-users spinning your wheel):</p>
              <ul className="space-y-1.5 list-none pl-0">
                <Bullet>Optional first name entered before spinning</Bullet>
                <Bullet>Prize outcome and timestamp of the spin</Bullet>
                <Bullet>Access code used to enter the wheel (single-use tokens generated by the shop owner)</Bullet>
              </ul>
              <p className="font-semibold" style={{ color: C.dark }}>Usage data collected automatically:</p>
              <ul className="space-y-1.5 list-none pl-0">
                <Bullet>Browser type and device information</Bullet>
                <Bullet>Pages visited, time spent, and actions taken within the platform</Bullet>
                <Bullet>IP address (used for security and abuse prevention)</Bullet>
              </ul>
            </Section>

            <Section title="2. Cookies & Tracking">
              <p>We use cookies and similar technologies to operate and improve our services.</p>
              <ul className="space-y-1.5 list-none pl-0">
                <Bullet><strong style={{ color: C.dark }}>Essential cookies:</strong> Required for authentication sessions and secure access to your account. Cannot be disabled without breaking core functionality.</Bullet>
                <Bullet><strong style={{ color: C.dark }}>Functional cookies:</strong> Remember your preferences such as reduced-motion settings and PWA install state.</Bullet>
                <Bullet><strong style={{ color: C.dark }}>Analytics cookies:</strong> Help us understand how the platform is used in aggregate so we can improve it. No personal profiles are built from this data.</Bullet>
              </ul>
              <p>You can control cookies through your browser settings. Disabling essential cookies will prevent you from logging in.</p>
            </Section>

            <Section title="3. How We Use Your Information">
              <ul className="space-y-1.5 list-none pl-0">
                <Bullet>To create and maintain your account and provide the Mystery Unlock service</Bullet>
                <Bullet>To process subscription payments and send billing-related communications</Bullet>
                <Bullet>To display your shop's prize wheel to your customers</Bullet>
                <Bullet>To detect, investigate, and prevent fraudulent or unauthorised use</Bullet>
                <Bullet>To send service-related communications (e.g. account approval, password resets)</Bullet>
                <Bullet>To improve and develop our platform based on aggregate usage patterns</Bullet>
              </ul>
              <p>We do not sell your personal information to third parties.</p>
            </Section>

            <Section title="4. Data Sharing">
              <p>We share your information only in the following circumstances:</p>
              <ul className="space-y-1.5 list-none pl-0">
                <Bullet><strong style={{ color: C.dark }}>Service providers:</strong> Infrastructure partners (hosting, database, authentication) who process data on our behalf under strict data processing agreements.</Bullet>
                <Bullet><strong style={{ color: C.dark }}>Payment processors:</strong> Your billing details are handled by PCI-compliant third-party processors. We receive only a tokenised reference.</Bullet>
                <Bullet><strong style={{ color: C.dark }}>Legal requirements:</strong> We may disclose information if required by law, court order, or to protect the rights and safety of Mystery Unlock and its users.</Bullet>
              </ul>
            </Section>

            <Section title="5. Data Security">
              <ul className="space-y-1.5 list-none pl-0">
                <Bullet>All data is transmitted over TLS (HTTPS) — never plain HTTP</Bullet>
                <Bullet>Row-level security is enforced on all user data tables in our database</Bullet>
                <Bullet>Access codes and spin results are not accessible via public APIs</Bullet>
                <Bullet>Administrative privileges (super-admin roles) can only be granted server-side</Bullet>
                <Bullet>Passwords are never stored in plain text — authentication is managed by our auth provider</Bullet>
              </ul>
              <p>No method of transmission or storage is 100% secure. We encourage you to use a strong, unique password for your account.</p>
            </Section>

            <Section title="6. Data Retention">
              <p>We retain your account data for as long as your account is active or as needed to provide our services.</p>
              <ul className="space-y-1.5 list-none pl-0">
                <Bullet>Spin records and access codes can be deleted by the shop owner at any time from the dashboard</Bullet>
                <Bullet>Upon account closure, we delete or anonymise your personal data within 30 days</Bullet>
                <Bullet>Billing records may be retained for up to 7 years to comply with financial regulations</Bullet>
              </ul>
            </Section>

            <Section title="7. Your Rights">
              <p>Depending on your location, you may have the right to:</p>
              <ul className="space-y-1.5 list-none pl-0">
                <Bullet>Access the personal data we hold about you</Bullet>
                <Bullet>Request correction of inaccurate data</Bullet>
                <Bullet>Request deletion of your account and associated personal data</Bullet>
                <Bullet>Object to or restrict certain processing of your data</Bullet>
                <Bullet>Receive a copy of your data in a portable format</Bullet>
              </ul>
              <p>
                To exercise these rights, email us at{" "}
                <a href="mailto:support@mysteryunlock.com" className="underline" style={{ color: C.primaryDark }}>
                  support@mysteryunlock.com
                </a>.
                We will respond within 30 days.
              </p>
            </Section>

            <Section title="8. Children's Privacy">
              <p>
                Mystery Unlock is not directed at children under the age of 13. We do not knowingly collect personal information from children under 13. If you believe a child has provided us with personal information, please contact us and we will delete it promptly.
              </p>
            </Section>

            <Section title="9. Changes to This Policy">
              <p>
                We may update this Privacy Policy from time to time. We will notify you of material changes by posting the new policy on this page with an updated "Last updated" date. Continued use of the platform after changes take effect constitutes your acceptance of the revised policy.
              </p>
            </Section>

            <Section title="10. Contact">
              <p>If you have questions about this Privacy Policy or our data practices, please contact us:</p>
              <div
                className="rounded-xl p-4 mt-2 text-sm"
                style={{ background: "white", border: `1px solid ${C.dark}10` }}
              >
                <strong style={{ color: C.dark }}>Mystery Unlock</strong><br />
                Email:{" "}
                <a href="mailto:support@mysteryunlock.com" className="underline" style={{ color: C.primaryDark }}>
                  support@mysteryunlock.com
                </a><br />
                Website:{" "}
                <a href="https://mysteryunlock.com" target="_blank" rel="noopener noreferrer" className="underline" style={{ color: C.primaryDark }}>
                  https://mysteryunlock.com
                </a>
              </div>
            </Section>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
