// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/auth-pages/ForgotPassword.tsx": () => import("../components/mockups/auth-pages/ForgotPassword.tsx"),
  "./components/mockups/auth-pages/SignIn.tsx": () => import("../components/mockups/auth-pages/SignIn.tsx"),
  "./components/mockups/auth-pages/SignUp.tsx": () => import("../components/mockups/auth-pages/SignUp.tsx")
};
