// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase, getClientId } from './client'
import { pushDebugEvent } from '@/lib/debug-auth-log'

// True when a Supabase auth session exists in localStorage — used to avoid
// pointless refresh attempts for anonymous visitors.
function hasStoredSession(): boolean {
  try {
    if (typeof window === 'undefined' || !window.localStorage) return false
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i)
      if (key && key.startsWith('sb-') && key.endsWith('-auth-token')) return true
    }
  } catch {}
  return false
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const _t0 = Date.now();
    const _isInBrowser = typeof window !== 'undefined';
    console.log("[attachSupabaseAuth] ENTER", { ts: new Date().toISOString(), clientId: getClientId(), isInBrowser: _isInBrowser });
    pushDebugEvent('auth-attacher.ts', 'attachSupabaseAuth', 'middleware:entered', { clientId: getClientId(), isInBrowser: _isInBrowser }, _isInBrowser ? 'info' : 'warn');
    const storedSessionExists = hasStoredSession();
    console.log("[attachSupabaseAuth] hasStoredSession():", storedSessionExists);
    pushDebugEvent('auth-attacher.ts', 'attachSupabaseAuth', 'hasStoredSession', { result: storedSessionExists }, storedSessionExists ? 'success' : 'warn');
    console.log("[attachSupabaseAuth] calling getSession() with clientId:", getClientId());
    let { data } = await supabase.auth.getSession()
    const sessionFromGetSession = !!data.session;
    let token = data.session?.access_token

    console.log("[attachSupabaseAuth] getSession() result:", {
      hasSession: sessionFromGetSession,
      hasToken: !!token,
      tokenPrefix: token?.slice(0, 12) ?? null,
      expiresAt: data.session?.expires_at ?? null,
    });
    pushDebugEvent('auth-attacher.ts', 'attachSupabaseAuth', 'getSession:result', {
      hasSession: sessionFromGetSession, hasToken: !!token, expiresAt: data.session?.expires_at ?? null,
    }, sessionFromGetSession ? 'success' : 'error');

    if (!token && storedSessionExists) {
      // A session exists in storage but wasn't returned (e.g. mobile tab
      // resume with an expired access token) — attempt one explicit refresh.
      console.log("[attachSupabaseAuth] token missing but stored session detected — attempting refreshSession()");
      pushDebugEvent('auth-attacher.ts', 'attachSupabaseAuth', 'refreshSession:attempt', {}, 'warn');
      const { data: refreshed } = await supabase.auth.refreshSession()
      token = refreshed.session?.access_token
      console.log("[attachSupabaseAuth] refreshSession() result:", {
        hasToken: !!token,
        tokenPrefix: token?.slice(0, 12) ?? null,
      });
      pushDebugEvent('auth-attacher.ts', 'attachSupabaseAuth', 'refreshSession:result', { hasToken: !!token }, !!token ? 'success' : 'error');
    }

    const hasAuthHeader = !!token;
    console.log("[attachSupabaseAuth] outgoing Authorization header present:", hasAuthHeader);
    pushDebugEvent('auth-attacher.ts', 'attachSupabaseAuth', 'outgoing:authHeader', { hasAuthHeader, storedSessionExists }, hasAuthHeader ? 'success' : 'error');

    if (!hasAuthHeader) {
      console.error("[attachSupabaseAuth] NO TOKEN — server fn will receive no Authorization header. storedSessionExists:", storedSessionExists);
    }

    console.log("[attachSupabaseAuth] EXIT", { elapsed: Date.now() - _t0, hasAuthHeader, jwtPrefix: token?.slice(0, 12) ?? null });

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
